In [4]:
import numpy as np

## 1.compute the mean, standard deviation, and variance of the given array along the second axis using numpy

In [3]:
data = np.array([[11, 22],[33, 44],[55, 66]])

In [9]:
#Mean using numpy.mean() inbuilt function
m1 = np.mean(data)
print("Mean with inbuilt method: ", m1)

#Mean using a formula
m2 = np.average(data)
print("Mean with a formula: ", m2)

Mean:  38.5
Mean:  38.5


In [10]:
#Standard deviation using numpy.std() inbuilt function
s1 = np.std(data)
print("Standard deviation with inbuilt method: ", s1)

#Standard deviation using a formula
s2 = np.sqrt(np.mean((data - np.mean(data)) ** 2))
print("Standard deviation with a formula: ", s2)

Standard deviation:  18.786076404259266
Standard deviation:  18.786076404259266


In [11]:
#Variance using numpy.var() inbuilt function
v1 = np.var(data)
print("Variance with inbuilt method: ", v1)

#Variance using a formula
v2 = np.mean((data - np.mean(data)) ** 2)
print("Variance with a formula: ", v2)

Variance with inbuilt method:  352.9166666666667
Variance with a formula:  352.9166666666667


### 2.reshape the above array to a one dimension array(one column)

In [14]:
data = np.array([[11, 22],[33, 44],[55, 66]])
print(data)
#shape of the array
print(np.shape(data))

#Reshaping the array to a 1D array, one column
data1 = np.reshape(data, (6,1))
print(data1)

[[11 22]
 [33 44]
 [55 66]]
(3, 2)
[[11]
 [22]
 [33]
 [44]
 [55]
 [66]]


## Use the data in the cell below to complete the following exercises

In [5]:
#lets create an array to work with
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

### 3. What is the average value of the second column (to two decimal places)

In [22]:
#Accessing data from the second column
column1 = random_integers[:,1]
print(column1)
#Average of the second column
column1avg = np.mean(column1)
print(column1avg)
#Round average to 2 decimal places
round(214895.8, 2)

[333008  42105 326386  49982 231729 343356 254634 406983 129585 335140
   8973  32213  56174 273338 282399 101115 425024 180346 449971  35455]
214895.8


214895.8

### 4. What is the sum of the first 5 rows of the third and fourth columns?

In [29]:
#Accessing the first 5 rows of the third and fourth columns
new_array = random_integers[:5, [2,3]]
print(new_array)

#Sum of the first 5 rows of the third and fourth columns 
print("Sum of all array elements: ", np.sum(new_array))

[[202553 140037]
 [261540 481981]
 [110795 394863]
 [408830 485118]
 [265455 109413]]
Sum of all array elements:  2860585


### 5. reverse the columns of the array

In [33]:
#Reverse the columns of the array using np.flip
print("Reversed array columns: \n", np.flip(random_integers, axis=0))

Reversed array columns: 
 [[476442  35455 191553 384154  29917]
 [ 11835 449971 494184 472031 353049]
 [ 52547 180346 178760 305186 262153]
 [148593 425024 348570 117968 107007]
 [198049 101115 419547 260219 325793]
 [ 38175 282399 318413 337639 379802]
 [225516 273338  73335 283013 212813]
 [246225  56174 244097   9350 496966]
 [  3975  32213 160603 275485 388234]
 [287650   8973 477425 382803 465168]
 [188411 335140 141681  59641 211420]
 [444899 129585 171318 313094 425041]
 [375059 406983 208947 115641 296685]
 [140473 254634 112262  25063 108262]
 [174677 343356 301717 224120 401101]
 [407675 231729 265455 109413 103399]
 [ 38317  49982 408830 485118  16119]
 [489984 326386 110795 394863  25024]
 [ 63857  42105 261540 481981 176739]
 [ 80842 333008 202553 140037  81969]]


### 6. Get the transpose of the array


In [32]:
#Transpose of array using inbuilt function 'T'
print("Transpose of array: \n", random_integers.T)

Transpose of array: 
 [[ 80842  63857 489984  38317 407675 174677 140473 375059 444899 188411
  287650   3975 246225 225516  38175 198049 148593  52547  11835 476442]
 [333008  42105 326386  49982 231729 343356 254634 406983 129585 335140
    8973  32213  56174 273338 282399 101115 425024 180346 449971  35455]
 [202553 261540 110795 408830 265455 301717 112262 208947 171318 141681
  477425 160603 244097  73335 318413 419547 348570 178760 494184 191553]
 [140037 481981 394863 485118 109413 224120  25063 115641 313094  59641
  382803 275485   9350 283013 337639 260219 117968 305186 472031 384154]
 [ 81969 176739  25024  16119 103399 401101 108262 296685 425041 211420
  465168 388234 496966 212813 379802 325793 107007 262153 353049  29917]]


##                                                      Pandas

### 1. Convert the above array (random integers) to a dataframe with column names; one, two, three, four, five

In [6]:
#Converting array into a dataframe with column names
import pandas as pd
df = pd.DataFrame(random_integers, columns = ['one', 'two', 'three', 'four', 'five'])
print(df)

       one     two   three    four    five
0    80842  333008  202553  140037   81969
1    63857   42105  261540  481981  176739
2   489984  326386  110795  394863   25024
3    38317   49982  408830  485118   16119
4   407675  231729  265455  109413  103399
5   174677  343356  301717  224120  401101
6   140473  254634  112262   25063  108262
7   375059  406983  208947  115641  296685
8   444899  129585  171318  313094  425041
9   188411  335140  141681   59641  211420
10  287650    8973  477425  382803  465168
11    3975   32213  160603  275485  388234
12  246225   56174  244097    9350  496966
13  225516  273338   73335  283013  212813
14   38175  282399  318413  337639  379802
15  198049  101115  419547  260219  325793
16  148593  425024  348570  117968  107007
17   52547  180346  178760  305186  262153
18   11835  449971  494184  472031  353049
19  476442   35455  191553  384154   29917


### 2. Show the summary statistics of the variables

### 3. Create a correlation matrix of the the five variables

In [7]:
#Summary statistics of the variables
df.describe()

one            two          three           four  \
count      20.000000      20.000000      20.000000      20.000000   
mean   204660.050000  214895.800000  254579.250000  258840.950000   
std    160901.903689  147813.419501  123604.500639  152653.178515   
min      3975.000000    8973.000000   73335.000000    9350.000000   
25%     61029.500000   54626.000000  168639.250000  117386.250000   
50%    181544.000000  243181.500000  226522.000000  279249.000000   
75%    309502.250000  333541.000000  325952.250000  383140.750000   
max    489984.000000  449971.000000  494184.000000  485118.000000   

                five  
count      20.000000  
mean   243333.050000  
std    156738.446671  
min     16119.000000  
25%    106105.000000  
50%    237483.000000  
75%    381910.000000  
max    496966.000000

In [8]:
#Create a correlation matrix of the five variables
correlationMatrix = df.corr()
print(correlationMatrix)

            one       two     three      four      five
one    1.000000 -0.045740 -0.298734 -0.129010 -0.135129
two   -0.045740  1.000000 -0.073682 -0.310364 -0.160247
three -0.298734 -0.073682  1.000000  0.372592  0.276976
four  -0.129010 -0.310364  0.372592  1.000000 -0.060995
five  -0.135129 -0.160247  0.276976 -0.060995  1.000000


### 4. Read the titanic dataset into a dataframe

In [33]:
#To read the dataset, we are going to use read_csv
#Import the dataset with read_csv
titanic_df = pd.read_csv("titanic3.csv")

#Checking first elements of the dataframe with .head() method
titanic_df.head() #first 5 elements of the dataframe
titanic_df.head(25) #first 25 elements of the dataframe

pclass  survived                                               name  \
0        1         1                      Allen, Miss. Elisabeth Walton   
1        1         1                     Allison, Master. Hudson Trevor   
2        1         0                       Allison, Miss. Helen Loraine   
3        1         0               Allison, Mr. Hudson Joshua Creighton   
4        1         0    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
5        1         1                                Anderson, Mr. Harry   
6        1         1                  Andrews, Miss. Kornelia Theodosia   
7        1         0                             Andrews, Mr. Thomas Jr   
8        1         1      Appleton, Mrs. Edward Dale (Charlotte Lamson)   
9        1         0                            Artagaveytia, Mr. Ramon   
10       1         0                             Astor, Col. John Jacob   
11       1         1  Astor, Mrs. John Jacob (Madeleine Talmadge Force)   
12       1         1                      Aubart, Mme. Leontine Pauline   
13       1         1                       Barber, Miss. Ellen "Nellie"   
14       1         1               Barkworth, Mr. Algernon Henry Wilson   
15       1         0                                Baumann, Mr. John D   
16       1         0                           Baxter, Mr. Quigg Edmond   
17       1         1    Baxter, Mrs. James (Helene DeLaudeniere Chaput)   
18       1         1                              Bazzani, Miss. Albina   
19       1         0                               Beattie, Mr. Thomson   
20       1         1                      Beckwith, Mr. Richard Leonard   
21       1         1   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)   
22       1         1                              Behr, Mr. Karl Howell   
23       1         1                              Bidois, Miss. Rosalie   
24       1         1                                  Bird, Miss. Ellen   

       sex    age  sibsp  parch    ticket      fare    cabin embarked boat  \
0   female  29.00      0      0     24160  211.3375       B5        S    2   
1     male   0.92      1      2    113781  151.5500  C22 C26        S   11   
2   female   2.00      1      2    113781  151.5500  C22 C26        S  NaN   
3     male  30.00      1      2    113781  151.5500  C22 C26        S  NaN   
4   female  25.00      1      2    113781  151.5500  C22 C26        S  NaN   
5     male  48.00      0      0     19952   26.5500      E12        S    3   
6   female  63.00      1      0     13502   77.9583       D7        S   10   
7     male  39.00      0      0    112050    0.0000      A36        S  NaN   
8   female  53.00      2      0     11769   51.4792     C101        S    D   
9     male  71.00      0      0  PC 17609   49.5042      NaN        C  NaN   
10    male  47.00      1      0  PC 17757  227.5250  C62 C64        C  NaN   
11  female  18.00      1      0  PC 17757  227.5250  C62 C64        C    4   
12  female  24.00      0      0  PC 17477   69.3000      B35        C    9   
13  female  26.00      0      0     19877   78.8500      NaN        S    6   
14    male  80.00      0      0     27042   30.0000      A23        S    B   
15    male    NaN      0      0  PC 17318   25.9250      NaN        S  NaN   
16    male  24.00      0      1  PC 17558  247.5208  B58 B60        C  NaN   
17  female  50.00      0      1  PC 17558  247.5208  B58 B60        C    6   
18  female  32.00      0      0     11813   76.2917      D15        C    8   
19    male  36.00      0      0     13050   75.2417       C6        C    A   
20    male  37.00      1      1     11751   52.5542      D35        S    5   
21  female  47.00      1      1     11751   52.5542      D35        S    5   
22    male  26.00      0      0    111369   30.0000     C148        C    5   
23  female  42.00      0      0  PC 17757  227.5250      NaN        C    4   
24  female  29.00      0      0  PC 17483  221.7792      C97        S    8   

     body               

### 5. Drop the name column

In [36]:
#Dropping the name column
titanic_df.drop('name', axis=1, inplace=True)
#Examine the dataframe again
titanic_df.head(25)

pclass  survived     sex    age  sibsp  parch    ticket      fare  \
0        1         1  female  29.00      0      0     24160  211.3375   
1        1         1    male   0.92      1      2    113781  151.5500   
2        1         0  female   2.00      1      2    113781  151.5500   
3        1         0    male  30.00      1      2    113781  151.5500   
4        1         0  female  25.00      1      2    113781  151.5500   
5        1         1    male  48.00      0      0     19952   26.5500   
6        1         1  female  63.00      1      0     13502   77.9583   
7        1         0    male  39.00      0      0    112050    0.0000   
8        1         1  female  53.00      2      0     11769   51.4792   
9        1         0    male  71.00      0      0  PC 17609   49.5042   
10       1         0    male  47.00      1      0  PC 17757  227.5250   
11       1         1  female  18.00      1      0  PC 17757  227.5250   
12       1         1  female  24.00      0      0  PC 17477   69.3000   
13       1         1  female  26.00      0      0     19877   78.8500   
14       1         1    male  80.00      0      0     27042   30.0000   
15       1         0    male    NaN      0      0  PC 17318   25.9250   
16       1         0    male  24.00      0      1  PC 17558  247.5208   
17       1         1  female  50.00      0      1  PC 17558  247.5208   
18       1         1  female  32.00      0      0     11813   76.2917   
19       1         0    male  36.00      0      0     13050   75.2417   
20       1         1    male  37.00      1      1     11751   52.5542   
21       1         1  female  47.00      1      1     11751   52.5542   
22       1         1    male  26.00      0      0    111369   30.0000   
23       1         1  female  42.00      0      0  PC 17757  227.5250   
24       1         1  female  29.00      0      0  PC 17483  221.7792   

      cabin embarked boat   body                        home.dest  
0        B5        S    2    NaN                     St Louis, MO  
1   C22 C26        S   11    NaN  Montreal, PQ / Chesterville, ON  
2   C22 C26        S  NaN    NaN  Montreal, PQ / Chesterville, ON  
3   C22 C26        S  NaN  135.0  Montreal, PQ / Chesterville, ON  
4   C22 C26        S  NaN    NaN  Montreal, PQ / Chesterville, ON  
5       E12        S    3    NaN                     New York, NY  
6        D7        S   10    NaN                       Hudson, NY  
7       A36        S  NaN    NaN                      Belfast, NI  
8      C101        S    D    NaN              Bayside, Queens, NY  
9       NaN        C  NaN   22.0              Montevideo, Uruguay  
10  C62 C64        C  NaN  124.0                     New York, NY  
11  C62 C64        C    4    NaN                     New York, NY  
12      B35        C    9    NaN                    Paris, France  
13      NaN        S    6    NaN                              NaN  
14      A23        S    B    NaN                    Hessle, Yorks  
15      NaN        S  NaN    NaN                     New York, NY  
16  B58 B60        C  NaN    NaN                     Montreal, PQ  
17  B58 B60        C    6    NaN                     Montreal, PQ  
18      D15        C    8    NaN                              NaN  
19       C6        C    A    NaN                     Winnipeg, MN  
20      D35        S    5    NaN                     New York, NY  
21      D35        S    5    NaN                     New York, NY  
22     C148        C    5    NaN                     New York, NY  
23      NaN        C    4    NaN                              NaN  
24      C97        S    8    NaN                              NaN

### 6.What is the relationship between age and fare

In [35]:
#Relationship between age and fare using corr(), corelationship
column_1 = titanic_df['age']
column_2 = titanic_df['fare']
relationship = column_1.corr(column_2)
print(relationship)

0.17873985599964118


### 7. Calculate the probability of survival

In [38]:
#Probability of survival
#Using .groupby() and the inbuilt .div()
survival_probs = titanic_df.groupby('survived').size().div(len(titanic_df))
print(survival_probs)

survived
0    0.618029
1    0.381971
dtype: float64
