In [1]:
import numpy as np

## 1.compute the mean, standard deviation, and variance of the given array along the second axis using numpy

In [2]:
data = np.array([[11, 22],[33, 44],[55, 66]])

In [3]:
#Write your code here
print("mean is",np.mean(data,axis = 0))
print("standard deviation is",np.std(data,axis =0))
print("variance",np.var(data))

mean is [33. 44.]
standard deviation is [17.96292478 17.96292478]
variance 352.9166666666667


### 2.reshape the above array to a one dimension array(one column)

In [4]:
#Write your code here
np.reshape(data,(6,1))

array([[11],
       [22],
       [33],
       [44],
       [55],
       [66]])

## Use the data in the cell below to complete the following exercises

In [5]:
#lets create an array to work with
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

### 3. What is the average value of the second column (to two decimal places)

In [6]:
#Write your code here
ave=(random_integers[:,1])
print("the average is:\n",np.average(ave))


the average is:
 214895.8


### 4. What is the sum of the first 5 rows of the third and fourth columns?

In [7]:
#Write your code here
add=(random_integers[:5,2:4])
print("the sum is:\n",np.sum(add))

the sum is:
 2860585


### 5. reverse the columns of the array

In [8]:
#Write your code here
np.flip(random_integers)


array([[ 29917, 384154, 191553,  35455, 476442],
       [353049, 472031, 494184, 449971,  11835],
       [262153, 305186, 178760, 180346,  52547],
       [107007, 117968, 348570, 425024, 148593],
       [325793, 260219, 419547, 101115, 198049],
       [379802, 337639, 318413, 282399,  38175],
       [212813, 283013,  73335, 273338, 225516],
       [496966,   9350, 244097,  56174, 246225],
       [388234, 275485, 160603,  32213,   3975],
       [465168, 382803, 477425,   8973, 287650],
       [211420,  59641, 141681, 335140, 188411],
       [425041, 313094, 171318, 129585, 444899],
       [296685, 115641, 208947, 406983, 375059],
       [108262,  25063, 112262, 254634, 140473],
       [401101, 224120, 301717, 343356, 174677],
       [103399, 109413, 265455, 231729, 407675],
       [ 16119, 485118, 408830,  49982,  38317],
       [ 25024, 394863, 110795, 326386, 489984],
       [176739, 481981, 261540,  42105,  63857],
       [ 81969, 140037, 202553, 333008,  80842]])

### 6. Get the transpose of the array


In [9]:
 #Write your code here
trans=random_integers.T
print("the transponse of the array is:\n",trans)

the transponse of the array is:
 [[ 80842  63857 489984  38317 407675 174677 140473 375059 444899 188411
  287650   3975 246225 225516  38175 198049 148593  52547  11835 476442]
 [333008  42105 326386  49982 231729 343356 254634 406983 129585 335140
    8973  32213  56174 273338 282399 101115 425024 180346 449971  35455]
 [202553 261540 110795 408830 265455 301717 112262 208947 171318 141681
  477425 160603 244097  73335 318413 419547 348570 178760 494184 191553]
 [140037 481981 394863 485118 109413 224120  25063 115641 313094  59641
  382803 275485   9350 283013 337639 260219 117968 305186 472031 384154]
 [ 81969 176739  25024  16119 103399 401101 108262 296685 425041 211420
  465168 388234 496966 212813 379802 325793 107007 262153 353049  29917]]


##                                                      Pandas

### 1. Convert the above array (random integers) to a dataframe with column names; one, two, three, four, five

In [10]:
#Write your code here
import pandas as pd
dataframe=pd.DataFrame(data=random_integers,columns=["one","two","three","four","five"])
print(dataframe)




       one     two   three    four    five
0    80842  333008  202553  140037   81969
1    63857   42105  261540  481981  176739
2   489984  326386  110795  394863   25024
3    38317   49982  408830  485118   16119
4   407675  231729  265455  109413  103399
5   174677  343356  301717  224120  401101
6   140473  254634  112262   25063  108262
7   375059  406983  208947  115641  296685
8   444899  129585  171318  313094  425041
9   188411  335140  141681   59641  211420
10  287650    8973  477425  382803  465168
11    3975   32213  160603  275485  388234
12  246225   56174  244097    9350  496966
13  225516  273338   73335  283013  212813
14   38175  282399  318413  337639  379802
15  198049  101115  419547  260219  325793
16  148593  425024  348570  117968  107007
17   52547  180346  178760  305186  262153
18   11835  449971  494184  472031  353049
19  476442   35455  191553  384154   29917


### 2. Show the summary statistics of the variables


In [11]:

print("the summarized statistics is:\n",dataframe.describe())

the summarized statistics is:
                  one            two          three           four  \
count      20.000000      20.000000      20.000000      20.000000   
mean   204660.050000  214895.800000  254579.250000  258840.950000   
std    160901.903689  147813.419501  123604.500639  152653.178515   
min      3975.000000    8973.000000   73335.000000    9350.000000   
25%     61029.500000   54626.000000  168639.250000  117386.250000   
50%    181544.000000  243181.500000  226522.000000  279249.000000   
75%    309502.250000  333541.000000  325952.250000  383140.750000   
max    489984.000000  449971.000000  494184.000000  485118.000000   

                five  
count      20.000000  
mean   243333.050000  
std    156738.446671  
min     16119.000000  
25%    106105.000000  
50%    237483.000000  
75%    381910.000000  
max    496966.000000  


### 3. Create a correlation matrix of the the five variables

In [12]:
#Write your code here
correlation= dataframe.corr()
print("The correlation matrix of the five variables:\n",correlation)

The correlation matrix of the five variables:
             one       two     three      four      five
one    1.000000 -0.045740 -0.298734 -0.129010 -0.135129
two   -0.045740  1.000000 -0.073682 -0.310364 -0.160247
three -0.298734 -0.073682  1.000000  0.372592  0.276976
four  -0.129010 -0.310364  0.372592  1.000000 -0.060995
five  -0.135129 -0.160247  0.276976 -0.060995  1.000000


### 4. Read the titanic dataset into a dataframe

In [13]:
#Write your code here
titanic=pd.read_csv("titanic3.csv")
titanic

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex    age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.00      0      0   24160  211.3375       B5        S    2   
1       male   0.92      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.00      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.00      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.00      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...    ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.50      1      0    2665   14.4542      NaN        C  NaN   
1305  female    NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.50      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.00      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.00      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

### 5. Drop the name column

In [16]:
#Write your code here
titanic.drop(columns=['name'])

pclass  survived     sex    age  sibsp  parch  ticket      fare  \
0          1         1  female  29.00      0      0   24160  211.3375   
1          1         1    male   0.92      1      2  113781  151.5500   
2          1         0  female   2.00      1      2  113781  151.5500   
3          1         0    male  30.00      1      2  113781  151.5500   
4          1         0  female  25.00      1      2  113781  151.5500   
...      ...       ...     ...    ...    ...    ...     ...       ...   
1304       3         0  female  14.50      1      0    2665   14.4542   
1305       3         0  female    NaN      1      0    2665   14.4542   
1306       3         0    male  26.50      0      0    2656    7.2250   
1307       3         0    male  27.00      0      0    2670    7.2250   
1308       3         0    male  29.00      0      0  315082    7.8750   

        cabin embarked boat   body                        home.dest  
0          B5        S    2    NaN                     St Louis, MO  
1     C22 C26        S   11    NaN  Montreal, PQ / Chesterville, ON  
2     C22 C26        S  NaN    NaN  Montreal, PQ / Chesterville, ON  
3     C22 C26        S  NaN  135.0  Montreal, PQ / Chesterville, ON  
4     C22 C26        S  NaN    NaN  Montreal, PQ / Chesterville, ON  
...       ...      ...  ...    ...                              ...  
1304      NaN        C  NaN  328.0                              NaN  
1305      NaN        C  NaN    NaN                              NaN  
1306      NaN        C  NaN  304.0                              NaN  
1307      NaN        C  NaN    NaN                              NaN  
1308      NaN        S  NaN    NaN                              NaN  

[1309 rows x 13 columns]

### 6.What is the relationship between age and fare

In [20]:
#Write your code here
print(titanic["age"].corr(titanic["fare"]))


0.17873985599964104


### 7. Calculate the probability of survival

In [29]:
#Write your code here

print("the probability of survival is :\n",(titanic['survived'].mean()))
print("the probability of survival based on the sex column is:\n ",(titanic.groupby(["sex"]).mean()['survived']))


the probability of survival is :
 0.3819709702062643
the probability of survival based on the sex column is:
  sex
female    0.727468
male      0.190985
Name: survived, dtype: float64
